//arithematicexception

import java.util.Scanner;
public class anand {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("Please enter a number: ");
        try
        {
            int num = scanner.nextInt();
            int result = 10 / num;
            System.out.println("Result: " + result);
        }
        catch (ArithmeticException e) {
            System.out.println("Exception caught: "+ e);
            System.out.println("Cannot divide by zero.");
        }
        catch (Exception e) {
            System.out.println("Exception caught: " + e);
            System.out.println("Invalid input.");
        }
    }
}

//arrayoutofindex

import java.util.Scanner;

public class anand {
    public static void main(String[] args){
        Scanner sc=new Scanner(System.in);
        int a[]=new int[5];
        try{
            for(int i=0;i<=5;i++){
                System.out.print("enter "+ (i+1)+" integer : ");
                a[i]= sc.nextInt();
            }
            for(int i=0;i<=5;i++){
                System.out.println(a[i]);
            }
            System.out.println("code execueted without any error");
        } catch(ArrayIndexOutOfBoundsException e){
            System.out.println("there was an error inside a code");
            System.out.println("error is due to"+e.getMessage());
        }
        System.out.println("application ended");
    }
}
